## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'thorlabs'  #for instance daqmx
package-url = 'https://github.com/CEMES-CNRS/pymodaq_plugins_thorlabs' #to modify
description = 'Set of PyMoDAQ plugins for instruments from Thorlabs (Kinesis K10CR1 (stepper rotation actuator), Kinesis Flipper, Kinesis KSP100, DCx camera...)'

author = 'SÃ©bastien Weber'
author-email = 'sebastien.weber@cemes.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pythonnet', 'pywin32', 'instrumental-lib>=0.6', 'nicelib', 'pylablib']
