## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'thorlabs'  #for instance daqmx
package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_thorlabs' #to modify
description = 'Set of PyMoDAQ plugins for instruments from Thorlabs (Kinesis K10CR1 (stepper rotation actuator), Kinesis Flipper, Kinesis KSP100, DCx camera...)'

author = 'SÃ©bastien Weber'
author-email = 'sebastien.weber@cemes.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ["pythonnet", "pywin32", "nicelib", "instrumental-lib", "pylablib", 'pymodaq>=4.0',
    'opencv-python']

[features]  # defines the plugin features contained into this plugin
instruments = true  # true if plugin contains instrument classes (else false, notice the lowercase for toml files)
extensions = false  # true if plugins contains dashboard extensions
pid_models = false  # true if plugins contains pid models
h5exporters = false  # true if plugin contains custom h5 file exporters
scanners = false  # true if plugin contains custom scan layout (daq_scan extensions)

